### ISSUE TITLE
Make error in Ubuntu 16

### ISSUE THREAD

**Issue by DwijadasDey** [FeCastle/tiptop#3]
Hi
      I have followed the following method of installing tiptop in Ubuntu 16.10 but make fails with the message 'undefined reference to `PAPI_library_init' .  libpapi-dev is already installed and the make should find it in the standard location.

**$ sudo apt-get install libncurses5-dev libncursesw5-dev libxml2-dev libpapi-dev byacc bison flex
$ wget https://github.com/FeCastle/tiptop/archive/master.zip
$ unzip master.zip
$ cd tiptop-master/
$ ./configure**
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking for a BSD-compatible install... /usr/bin/install -c
checking for initscr in -lcurses... yes
checking for xmlParseFile in -lxml2... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
**checking linux/perf_counter.h usability... no
checking linux/perf_counter.h presence... no
checking for linux/perf_counter.h... no**
checking linux/perf_event.h usability... yes
checking linux/perf_event.h presence... yes
checking for linux/perf_event.h... yes
checking hardware... x86
checking for inline... inline
checking for int32_t... yes
checking for int64_t... yes
checking for pid_t... yes
checking for uid_t in sys/types.h... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for gettimeofday... yes
checking for memset... yes
checking for select... yes
checking for strdup... yes
checking for strerror... yes
checking for strstr... yes
checking for uname... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: config.h is unchanged

**$ make**
cd src && make all
make[1]: Entering directory '/root/tiptop-master/src'
gcc -o tiptop tiptop.o pmc.o process.o requisite.o conf.o screen.o debug.o version.o helpwin.o options.o hash.o spawn.o xml-parser.o target.o utils-expression.o error.o lex.yy.o y.tab.o  -lxml2 -lcurses 
tiptop.o: In function `main':
/root/tiptop-master/src/tiptop.c:847: undefined reference to `PAPI_library_init'
/root/tiptop-master/src/tiptop.c:850: undefined reference to `PAPI_multiplex_init'
process.o: In function `done_proc':
/root/tiptop-master/src/process.c:103: undefined reference to `PAPI_cleanup_eventset'
/root/tiptop-master/src/process.c:104: undefined reference to `PAPI_destroy_eventset'
process.o: In function `handle_error':
/root/tiptop-master/src/process.c:41: undefined reference to `PAPI_strerror'
process.o: In function `new_processes':
/root/tiptop-master/src/process.c:375: undefined reference to `PAPI_create_eventset'
/root/tiptop-master/src/process.c:378: undefined reference to `PAPI_assign_eventset_component'
/root/tiptop-master/src/process.c:381: undefined reference to `PAPI_set_multiplex'
/root/tiptop-master/src/process.c:394: undefined reference to `PAPI_event_name_to_code'
/root/tiptop-master/src/process.c:395: undefined reference to `PAPI_add_event'
/root/tiptop-master/src/process.c:424: undefined reference to `PAPI_num_events'
/root/tiptop-master/src/process.c:427: undefined reference to `PAPI_attach'
/root/tiptop-master/src/process.c:430: undefined reference to `PAPI_start'
/root/tiptop-master/src/process.c:434: undefined reference to `PAPI_cleanup_eventset'
/root/tiptop-master/src/process.c:435: undefined reference to `PAPI_destroy_eventset'
utils-expression.o: In function `get_counter_value':
/root/tiptop-master/src/utils-expression.c:228: undefined reference to `PAPI_event_name_to_code'
/root/tiptop-master/src/utils-expression.c:237: undefined reference to `PAPI_get_opt'
/root/tiptop-master/src/utils-expression.c:247: undefined reference to `PAPI_num_events'
/root/tiptop-master/src/utils-expression.c:248: undefined reference to `PAPI_num_events'
/root/tiptop-master/src/utils-expression.c:271: undefined reference to `PAPI_read'
/root/tiptop-master/src/utils-expression.c:268: undefined reference to `PAPI_accum'
collect2: error: ld returned 1 exit status
Makefile:37: recipe for target 'tiptop' failed
make[1]: *** [tiptop] Error 1
make[1]: Leaving directory '/root/tiptop-master/src'
Makefile:31: recipe for target 'all' failed
make: *** [all] Error 2

Regards

**Comment by FeCastle** [comment]
Thanks for the report.  I have not built this in quite some time.  I saw a merge request from a while ago that looks like it may fix the issue.  I merged this into the master.  If you want to see if this resolves the issue, that would be great.

Deron
